# Generated by Django 4.2.5 on 2023-09-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_published_at', models.DateTimeField(verbose_name='date published')),
                ('post_url', models.URLField()),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
